paulaapp/urls.py
from django.urls import path
from .views import ProspectListView, ProspectDetailView, ProspectAddView, HomePageView, ProspectDeleteView, ToDoListView, ProspectEditView


urlpatterns = [
    path('', ProspectListView.as_view(), name='prospect-list'),
    path('add/', ProspectAddView.as_view(), name='prospect-add'),
    path('<uuid:pk>/edit', ProspectEditView.as_view(), name='prospect-edit'),
    path('<uuid:pk>/', ProspectDetailView.as_view(), name='prospect-details'),
    path('<uuid:pk>/delete/', ProspectDeleteView.as_view(), name='prospect-delete'),
    path('to-do/', ToDoListView.as_view(), name='to-do-list'),
]

paulasite/urls.py
from django.contrib import admin


from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from paulaapp.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('prospects/', include('paulaapp.urls')),
]

paulaapp/models.py
from django.db import models

import uuid
from django_extensions.db.models import TimeStampedModel
from django.core.validators import MaxValueValidator, MinValueValidator
import logging
import datetime
from uuid_upload_path import upload_to
from django.utils.translation import ugettext_lazy as _

log = logging.getLogger(__name__)


class UUIDModel(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)

    class Meta:
        abstract = True


class TimeStampedUUIDModel(TimeStampedModel, UUIDModel):    #inheriting fields from UUID and TimeStampedModel
    class Meta:
        abstract = True


class Prospect(TimeStampedUUIDModel):
    SUNDAY = 'SUN'
    SATURDAY = 'SAT'
    DAY_CHOICES = (
        (SATURDAY, 'Saturday'),
        (SUNDAY, 'Sunday',)
    )
    RENT = 'R'
    OWN = 'O'
    UNKNOWN = 'U'
    LIVING_CHOICES = (
        (RENT, 'Renting'),
        (OWN, 'Own property'),
        (UNKNOWN, 'Unknown')
    )
    HIGH = 'HI'
    LOW = 'LO'
    MIDDLE = 'MI'
    PURCHASED = 'PU'
    PRIORITY_CHOICES = (
        (HIGH, 'High'),
        (LOW, 'Low'),
        (MIDDLE, 'Middle'),
        (PURCHASED, 'Purchased')
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    prospect_email = models.EmailField(max_length=100)
    prospect_phone = models.CharField(max_length=12, default=None)  # opportunity to reformat this later
    date_added = models.DateField(("Date"), auto_now_add=True)
    first_visit_day_of_week = models.CharField(max_length=3, choices=DAY_CHOICES)
    referral_source = models.CharField(max_length=50)
    multiple_visits: bool = models.BooleanField(default=False)
    date_most_recent_visit = models.DateField(null=True)
    rent_or_own = models.CharField(max_length=1, choices=LIVING_CHOICES)
    buy_new_construction_only: bool = models.BooleanField(default=False)
    claims_agent: bool = models.BooleanField(default=False)
    notes = models.TextField(max_length=1000, blank=True)
    priority = models.CharField(max_length=2, choices=PRIORITY_CHOICES)
    prospect_card = models.FileField(upload_to=upload_to, blank=True, null=True)
    action_item = models.CharField(blank=True, null=True, max_length=100)
    action_date = models.DateField(blank=True, null=True)

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Prospect._meta.fields]

    class Meta:     #lets you define superficial things (.latest) used outside the database
        ordering = ['-date_most_recent_visit']

    def __str__(self):  #   when you print, what shows up
        return '{} {}'.format(self.first_name, self.last_name)


class Visit(TimeStampedUUIDModel):
    visit_date = models.DateField()
    visit_notes = models.CharField(max_length=100)
    prospect = models.ForeignKey(Prospect, on_delete=models.CASCADE, related_name='visits')

    class Meta:
        ordering = ['-visit_date']
        get_latest_by = ['visit_date']

    def __str__(self):
        return '{}'.format(self.visit_date)

paulaapp/forms.py
from django import forms
from .models import Prospect, Visit
from django.forms import inlineformset_factory
from bootstrap_datepicker_plus import DatePickerInput


class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        exclude = ('prospect',)
        widgets = {
            'visit_date': forms.DateInput(format='%m/%d/%Y', attrs={
                'placeholder': 'mm/dd/yyyy'
            }),
            'visit_notes': forms.TextInput(attrs={
                'placeholder': 'Visit notes'
            })
        }
    # visit_date = forms.DateField()
    # visit_notes = forms.CharField(max_length=100)


ProspectVisitFormSet = inlineformset_factory(Prospect, Visit, form=VisitForm, can_delete=True,
                                             fields=('visit_date', 'visit_notes', 'prospect'), extra=1)

paulaapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy
from .models import Prospect, Visit
from django.db.models import Q
from .forms import VisitForm, ProspectVisitFormSet
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.contrib.auth.mixins import LoginRequiredMixin


class ProspectListView(LoginRequiredMixin, ListView):
    model = Prospect
    template_name = 'paulaapp/prospect_list.html'
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            q = Q()
            # notes_found = Prospect.objects.filter(notes__icontains=query)
            # fname_found = Prospect.objects.filter(first_name__icontains=query)
            # lname_found = Prospect.objects.filter(last_name__icontains=query)
            q |= Q(notes__icontains=query)
            q |= Q(first_name__icontains=query)
            q |= Q(last_name__icontains=query)
            # found = notes_found.union(fname_found, lname_found).order_by('-date_most_recent_visit').distinct()
            return Prospect.objects.filter(q).distinct()
        else:
            return Prospect.objects.all()


class ProspectEditView(LoginRequiredMixin, UpdateView):
    model = Prospect
    fields = '__all__'
    # template_name = 'paulaapp/prospect_form.html'
    template_name = 'paulaapp/prospect_edit.html'
    success_url = reverse_lazy('prospect-list')

    def get(self, request, *args, **kwargs):  # Initialize and pass into context data
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        visits_formset = ProspectVisitFormSet(instance=self.object, prefix='visits_fs')

        formset_dict = {'visits_form': visits_formset}
        return self.render_to_response(
            self.get_context_data(form=form, **formset_dict)
        )

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        visits_formset = ProspectVisitFormSet(self.request.POST, instance=self.object, prefix='visits_fs')

        formset_dict = {'visits_form': visits_formset}
        if form.is_valid() and visits_formset.is_valid():
            return self.form_valid(form, formset_dict)
        else:
            return self.form_invalid(form, formset_dict)

    def form_valid(self, form, formsets):
        self.object = form.save()
        for formset_name in formsets.keys():
            formset = formsets[formset_name]
            formset.instance = self.object  # ties it to the correct Prospect
            formset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formsets):
        print('invalid form')
        return self.render_to_response(
            self.get_context_data(form=form, **formsets)
        )

    def get_success_url(self):
        return reverse_lazy('prospect-list')


class ProspectAddView(LoginRequiredMixin, CreateView):
    model = Prospect
    fields = '__all__'
    template_name = 'paulaapp/prospect_form.html'
    success_url = reverse_lazy('prospect-list')


class ProspectDeleteView(LoginRequiredMixin, DeleteView):
    model = Prospect
    fields = '__all__'
    template_name = 'paulaapp/prospect_confirm_delete.html'
    success_url = reverse_lazy('prospect-list')


class ProspectDetailView(LoginRequiredMixin, DetailView):
    model = Prospect
    template_name = 'paulaapp/prospect_details.html'


class HomePageView(LoginRequiredMixin, TemplateView):
    template_name = 'paulaapp/home_page.html'


class ToDoListView(LoginRequiredMixin, ListView):
    model = Prospect
    template_name = 'paulaapp/to_do_list.html'

    def get_queryset(self): #gets everything shown on page
        queryset = super(ToDoListView, self).get_queryset()
        queryset = queryset.order_by('action_date')
        return queryset


class IchijoCardView(LoginRequiredMixin, DetailView):
    model = Prospect

paulaapp/templates/paulaapp/home_page.html
<html>
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'paulaapp/css/base.css' %}"/>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Paulished</title>

</head>

<body>
<div class="container">
    <div class="header">
        <h7>Paulished</h7>
    </div>
    <br><br>
    <div class="col-12 text-center">
         <a id = "to_do_home" href="{% url 'to-do-list' %}" class="btn btn-outline-dark btn-lg">TO-DO</a>
         <a id = "prospect_btn" href="{% url 'prospect-list' %}" class="btn btn-outline-dark btn-lg">PROSPECTS</a>
    </div>
{#    <div class="col-12 text-center">#}
{#         <a id = "prospect_btn" href="{% url 'prospect-list' %}" class="btn btn-outline-dark btn-lg">PROSPECTS</a>#}
{#    </div>#}
</div>






</body>
</html>

paulaapp/templates/paulaapp/prospect_confirm_delete.html
<html>
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'paulaapp/css/base.css' %}"/>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <title>Delete Prospect</title>
</head>

<body>

    <div class="container">
        <div class="header">
            <h1><a class="paulished-link" href="{% url 'home' %}">Paulished</a></h1>
        </div>
        <div class="confirm-delete"><br><br>
            <div class="card border-HI">
                <div class="plate">
                    <div class="card-body">
                        <form method="post">{% csrf_token %}
                        <br><p>Are you sure you want to delete <b>{{ object }}</b> as a Prospect?<br><br>
                        <input type="submit" value="Confirm"></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

paulaapp/templates/paulaapp/prospect_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'paulaapp/css/base.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <meta charset="UTF-8">
    <title>{{ prospect }}</title>
</head>
<body>
    <div class="container">
        <div class="header">
          <h1><a class="paulished-link" href="{% url 'home' %}">Paulished</a></h1><br><br>
        </div>


        <div class="prospect-details">
            <div class="prospect-details border-{{ object.priority }}">
                    <div class="plate-detail">
                        <div class="card-body single">
                            <div class="proscenter"><h9 class="prosdetails">{{ object.first_name }} {{ object.last_name }}</h9></div><br>
                            <div class="row">
                                <div class="col-auto">
                                    <h10>Prospect email:  </h10><h11>{{ object.prospect_email }}</h11>
                                </div>
                                <div class="ml-auto">
                                    <h12>Prospect phone:  </h12><h13>{{ object.prospect_phone }}</h13>
                                </div>
                            </div><br><br>
                            <div class="row">
                                <div class="col-auto">
                                    <h10>Referral source:  </h10><h11>{{ object.referral_source }}</h11>
                                </div>
                                <div class="ml-auto">
                                    <h12>Rent or own:  </h12><h13> {{ object.get_rent_or_own_display }}</h13>
                                </div>
                            </div><br><br>
                            <div class="row">
                                <div class="col-auto">
                                    <h12>Buy new construction only:  </h12>
                                        <h13>Yes</h13>
                                </div>
                                <div class="ml-auto">
                                    <h12>Claims agent:  </h12><h13> {{ object.claims_agent }}</h13>
                                </div>
                            </div><br><br>
                            <div class="row">
                                <div class="col-auto">
                                    <h12>Notes:  </h12><h13>{{ object.notes }}</h13>
                                </div>
                                <div class="ml-auto">
                                    <h12>Priority:  </h12><h13> {{ object.get_priority_display }}</h13>
                                </div>
                            </div><br><br>
                            <div class="row">
                                <div class="col-auto">
                                    <h12>Action item:  </h12><h13> {{ object.action_item }}</h13>
                                </div>
                                <div class="ml-auto">
                                    <h12>Action date:  </h12><h13> {{ object.action_date }}</h13>
                                </div>
                            </div><br><br>
                            <div class="row">
                                <div class="col-auto">
                                    <h12>First visit day of week:  </h12><h13>{{ object.get_first_visit_day_of_week_display }}</h13>
                                </div>
                                <div class="ml-auto">
                                    <h12>Visits:  </h12>
                                    <h13>
                                        <table>
                                        {% for visit in object.visits.all %}
                                            <div>
                                                <tr>
                                                    <td width="100%">{{ visit.visit_date }}</td>
                                                    <td width="100%">{{ visit.visit_notes }}</td>
                                                </tr>
                                            </div>
                                        {% endfor %}
                                        </table>
                                    </h13>
                                </div>
                            </div><br><br>


                        </div>
                    </div>
            </div>
        </div>
    </div>
</body>
</html>

paulaapp/templates/paulaapp/prospect_edit.html
<html>
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'paulaapp/css/base.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <title>Edit Prospect</title>
</head>


<body>
{# Display a form #}
<div class="container">
    <div class="header">
        <h6>EDIT PROSPECT</h6>
        <form action="" method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="form row align-items-center inline">
{#                <div class="form-group col-auto">#}
{#                    <label>First name</label>#}
{#                    {{ form.first_name }}#}
{#                </div>#}
{##}
{#                <div class="form-group col-auto">#}
{#                    <label>Last name</label>#}
{#                    {{ form.last_name }}#}
{#                </div>#}
            </div>
            Visits
            <br><br><fieldset class="col">
                    {{ visits_form.management_form }}
                    {{ visits_form.non_form_errors }}
                    {% for fs in visits_form %}
                        {{ fs.id }}
                        <div class="form-row align-items-center inline">
                            <div class="form-group col-auto">
                                {{ fs.visit_date.errors }}
                                {{ fs.visit_date }}
                            </div>
                            <div class="form-group col-auto">
                                {{ fs.visit_date.errors }}
                                {{ fs.visit_notes }}
                            </div>
                        </div>
                    {% endfor %}
            </fieldset>

            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Submit
                </button>
                <a href="{% url 'prospect-delete' pk=prospect.id %}" class="btn btn-danger" role="button">Delete Prospect</a>
            {% endbuttons %}
        </form>
    </div>
</div>
</body>

</html>

paulaapp/templates/paulaapp/prospect_form.html
<html>
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'paulaapp/css/base.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <script src="{% static 'paulaapp/js/bootstrap-datepicker.js' %}"></script>
    <script type="text/javascript">
        $(document).ready( function () {
            $('.date').datepicker({
               format: 'mm/dd/yyyy',
               autoclose: true,
                assumeNearbyYear: true,
            });
        })
    </script>
    <title>Add Prospect</title>
</head>


<body>
{# Display a form #}
    <div class="container">
            <div class="header">
              <h6>ADD PROSPECT</h6>
                <form action="" method="post" class="form" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% bootstrap_form form %}
                  {% buttons %}
                    <button type="submit" class="btn btn-primary">
                      Submit
                    </button>
                  {% endbuttons %}
                 </form>
            </div>
    </div>
</body>

</html>

paulaapp/templates/paulaapp/prospect_list.html
<html>
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'paulaapp/css/base.css' %}"/>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <script src="{% static 'paulaapp/js/fitty.min.js' %}" ></script>
    <title>Paulished Prospects</title>
</head>

<body>
    <div class="container">
        <div class="header">
          <h1><a class="paulished-link" href="{% url 'home' %}">Paulished</a></h1>
            <h2>KNOLLS VISITORS</h2>
            <div class="container">
                <form method="GET" action="" id="search form">
                    <div class="row">
                        <a id = "add_button" href="add/" class="btn btn-outline-dark col-auto nav-button">ADD PROSPECT</a>
                        <div class="input-group col justify-content-center">
                            <input class="form-control col-4" id="search box" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search"/>
                            <button class="search_submit btn btn-outline-dark" type="submit">Search</button>
                        </div>
                        <a id = "to_do" href="to-do/" class="btn btn-outline-dark col-auto ml-auto nav-button">TO-DO</a>
                    </div>
                </form>
            </div>
        </div>



        <ul>
         <div class="row">
        {% for prospect in object_list %}

                <div class="col-4">

                        <div class="card border-{{ prospect.priority }}">
                            <div class="plate">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        {{ prospect.first_name }} {{ prospect.last_name }}
                                    </h5>
                                    <p class="card-text">
                                        Most recent visit:<br>
                                        {{ prospect.visits.latest.visit_date|date:'m/d/Y' }}
                                    </p>
                                    <a href="{% url 'prospect-edit' pk=prospect.id %}" class="btn btn-outline-danger btm-sm float-left" role="button">Edit</a>
                                    <a href="{% url 'prospect-details' pk=prospect.id %}" class="btn btn-outline-primary btm-sm float-right">Flip</a>
                                </div>
                            </div>
                        </div>
                </div>

        {#   <li><a href="{{  prospect.id }}">{{ prospect.first_name }} {{ prospect.last_name }}, {{ prospect.prospect_email }}, {{ prospect.prospect_phone }}</li>#}
        {% endfor %}
         </div>
        </ul>

    </div>

<script>
    fitty('h5.card-title', {
        minSize: 24,
        multiLine: true,

    });
</script>
</body>

</html>

paulaapp/templates/paulaapp/to_do_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'paulaapp/css/base.css' %}"/>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <title>To Do</title>
</head>
<body>
    <div class="container">
        <div class="header">
          <h1><a class="paulished-link" href="{% url 'home' %}">Paulished</a></h1>
            <h2>ACTION ITEMS</h2>
        </div>
        <div class="center-button">
            <a id = "prospect_btn" href="{% url 'prospect-list' %}" class="btn btn-outline-dark btn-sm">PROSPECTS</a>
        </div>
            <table style="width:100%">
                <tr>
                    <th>Name</th>
                    <th>Action</th>
                    <th>Due Date</th>
                </tr>
                {% for prospect in object_list %}
                    {% if prospect.action_item %}
                        <tr>
                            <td><a href="{% url 'prospect-details' pk=prospect.id %}">{{ prospect.first_name }} {{ prospect.last_name }}</a></td>
                            <td>{{ prospect.action_item }}</td>
                            <td>{{ prospect.action_date }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </table>
    </div>
</body>
</html>